# Meta Data for SEO

## Homepage
title = "Ubunchuu Trường Ú"
titleSeparator = " "
titleAddition = "Linux made easy."
description = "Ubunchuu Trường Ú là một dự án do một nhóm sinh viên trường KHTN lập nên, mong muốn cung cấp kiến thức bổ ích về linux và giúp các bạn học sinh, sinh viên bước đầu tiếp cận với hệ điều hành linux."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["images/linux-transparent.png"]
ogLocale = "en_US"
domainTLD = "https://ubunchuu-truong-us.github.io/"
titleHome = "Ubunchuu Trường Ú"

## Twitter Cards
# twitterSite = "@getdoks"
# twitterCreator = "@henkverlinde"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Ubunchuu Trường Ú"
# schemaAuthor = "Henk Verlinde"
# schemaAuthorTwitter = "https://twitter.com/henkverlinde"
# schemaAuthorLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
# schemaAuthorGitHub = "https://github.com/ubunchuu-truong-us"
schemaLocale = "en-US"
schemaLogo = "images/linux-transparent.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "images/linux-transparent.png"
schemaImageWidth = 1280
schemaImageHeight = 640
# schemaTwitter = "https://twitter.com/getdoks"
# schemaLinkedIn = ""
schemaGitHub = "https://github.com/ubunchuu-truong-us"
schemaSection = "docs"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images - Temporarily left in place for backward compatibility
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "linux-transparent.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://www.github.com/\">Github Pages</a>, <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2022 Ubunchuu Trường Ú"

# Alert
alert = true
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Ubunchuu Trường Ú đã quay trở lại sau kỳ thi cuối kỳ!"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/ubunchuu-truong-us/ubunchuu-truong-us.github.io"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = true
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = true
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
